name: packages

on: [push]

jobs:
    compile:
        name: Build
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Run the build process with Docker
            uses: addnab/docker-run-action@v3
            with:
                image: almalinux:8
                run: |
                  yum -yq install git rpm-build epel-release
                  python --version
                  python3.6 setup.py bdist_rpm --python /usr/bin/python3.6
